#!/bin/bash

if [ "$(which dialog)" == "" ]; then
	echo "dialog package must be installed: sudo apt-get install dialog"
	exit 1
fi

NON_CURRENT_BRANCHES="$(git branch | grep -v \\*)"
BRANCH_COUNT="$(git branch | wc -l)"
CURRENT_BRANCH=$(git rev-parse --symbolic-full-name --abbrev-ref HEAD)

DIALOG_MENU_ITEMS="$CURRENT_BRANCH \"$(git branch -v --list $CURRENT_BRANCH | tr -s ' ' | cut -f 3- -d ' ' | sed 's/"/\\"/g')\""
for BRANCH in $NON_CURRENT_BRANCHES; do
	BRANCH_DETAILS="$(git branch -v --list $BRANCH | tr -s ' ' | cut -f 3- -d ' ')"
	BRANCH_DETAILS="$(echo $BRANCH_DETAILS | sed 's/"/\\"/g')"
	DIALOG_MENU_ITEMS="$DIALOG_MENU_ITEMS $BRANCH \"$BRANCH_DETAILS\""
done

# if there are more branches than this, user will need to scroll up and down in list
MAX_MENU_ITEMS_ON_SCREEN_AT_ONCE=60

let DIALOG_MENU_WIDTH="$(git branch -v | awk '{ print length }' | sort -n | tail -1)+8"
if [ $BRANCH_COUNT -gt $MAX_MENU_ITEMS_ON_SCREEN_AT_ONCE ]; then
	let "DIALOG_MENU_HEIGHT=$MAX_MENU_ITEMS_ON_SCREEN_AT_ONCE+7"
else
	let "DIALOG_MENU_HEIGHT=$BRANCH_COUNT+7"
fi

# --keep-tite means that 'dialog' wont do "tput smcup" on startup
DIALOG_CMD="dialog --keep-tite --menu 'Select branch'  $DIALOG_MENU_HEIGHT  $DIALOG_MENU_WIDTH  $DIALOG_MENU_HEIGHT  $DIALOG_MENU_ITEMS"

TEMPFILE="/tmp/branch_name_$(date +%Y%m%d_%H%M%S)"
tput smcup
sh -c "$DIALOG_CMD" 2> $TEMPFILE
EXIT_CODE=$?
tput rmcup
if [ "$EXIT_CODE" == "0" ]; then
	git co $(cat $TEMPFILE)
fi
rm $TEMPFILE

