#!/bin/bash

if [ "$1" == "" ]; then
    echo "USAGE: $0 s/BLAH/YADA/g";
    echo "       or";
    echo "       $0 WHATEVER REPLACEMENT";
    return;
fi;
if [ "$2" != "" ]; then
    PATTERN="s#$1#$2#g";
else
    if [ "$(echo $1 | grep /)" != "" ]; then
        echo "error: \$1 may not contain /";
        return;
    fi;
    PATTERN="$1";
fi;

$(find-gnu-find) -type f -and ! -path '*/.git/*' -and ! -name .git | $(find-gnu-xargs) -I FILE $(find-gnu-sed) -i "$PATTERN" FILE
