#!/bin/bash

if [ "$(which dialog)" == "" ]; then
	echo "dialog package must be installed: sudo apt-get install dialog"
	exit 1
fi

SUBDIRS="$(find -mindepth 1 -maxdepth 1 -type d | sort)"
SUBDIR_COUNT="$(find -mindepth 1 -maxdepth 1 -type d | wc -l)"

if [ "$SUBDIR_COUNT" == "0" ]; then
	echo "The current directory has no sub-directories."
	exit 0
fi

DIALOG_MENU_ITEMS=""
for SUBDIR in $SUBDIRS; do
	DIALOG_MENU_ITEMS="$DIALOG_MENU_ITEMS $SUBDIR \"\" off"
done

# if there are more subdirs than this, user will need to scroll up and down in list
MAX_MENU_ITEMS_ON_SCREEN_AT_ONCE=60

let DIALOG_MENU_WIDTH="$(find -mindepth 1 -maxdepth 1 -type d | wc -L)+12"
if [ $SUBDIR_COUNT -gt $MAX_MENU_ITEMS_ON_SCREEN_AT_ONCE ]; then
	let "DIALOG_MENU_HEIGHT=$MAX_MENU_ITEMS_ON_SCREEN_AT_ONCE+7"
else
	let "DIALOG_MENU_HEIGHT=$SUBDIR_COUNT+7"
fi

DIALOG_CMD="dialog --checklist 'Check subdirs to delete:'  $DIALOG_MENU_HEIGHT  $DIALOG_MENU_WIDTH  $SUBDIR_COUNT  $DIALOG_MENU_ITEMS"

TEMPFILE="/tmp/subdirs_to_nuke_$(date +%Y%m%d_%H%M%S)"
sh -c "$DIALOG_CMD" 2> $TEMPFILE
clear
echo "Nuking subdirs: $(cat $TEMPFILE)"
echo "rm -rf $(cat $TEMPFILE)" | sh
rm $TEMPFILE
echo
echo "Remaining subdirs:"
echo
find -mindepth 1 -maxdepth 1 -type d
echo
